<?php

function iegs_form_alter(&$form, &$form_state, $form_id) {
	if($form_id == "registrations_node_form")
	{
		$form['title']['#size'] = 35;
		$form['title']['#maxlength'] = 35;
		$form['actions']['submit']['#value'] = 'Register';
		drupal_set_title('Register');
	}
	if($form_id == "user-login")
	{
		drupal_set_title('Login');
	}
	if(arg(0) == 'user' && arg(1) == 'login') {
    		drupal_set_title(t('Log in'));
  	}
}

?>